### ISSUE TITLE
Troubles with starting 

### ISSUE THREAD

**Issue by LevT2** [manifold-systems/manifold-sample-rest-api#1]
Hello
Please help with starting
Perhaps step-by-step instructions are needed

Fresh Idea Commnity, added the plugin, 
manually added -Xplugin:Manifold to Javac options -> Additional command-line parameters

Information:java: An exception has occurred in the compiler (12.0.2). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
Information:java: java.lang.UnsupportedOperationException
Information:java: 	at java.compiler@12.0.2/javax.tools.JavaFileManager.getServiceLoader(JavaFileManager.java:527)
Information:java: 	at jdk.compiler/com.sun.tools.javac.main.DelegatingJavaFileManager.getServiceLoader(DelegatingJavaFileManager.java:158)
Information:java: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Information:java: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Information:java: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Information:java: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
Information:java: 	at org.jetbrains.jps.javac.JavacMain$2.invoke(JavacMain.java:290)
Information:java: 	at com.sun.proxy.$Proxy24.getServiceLoader(Unknown Source)
Information:java: 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.initProcessorLoader(JavacProcessingEnvironment.java:266)
Information:java: 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.<init>(JavacProcessingEnvironment.java:237)
Information:java: 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.instance(JavacProcessingEnvironment.java:193)
Information:java: 	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:208)
Information:java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:199)
Information:java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:101)
Information:java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
Information:java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
Information:java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
Information:java: 	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:195)
Information:java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:460)
Information:java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:330)
Information:java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:255)
Information:java: 	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:213)
Information:java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1324)
Information:java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1004)
Information:java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1071)
Information:java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:965)
Information:java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:794)
Information:java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:376)
Information:java: 	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
Information:java: 	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:139)
Information:java: 	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:288)
Information:java: 	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:121)
Information:java: 	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:228)
Information:java: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Information:java: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Information:java: 	at java.base/java.lang.Thread.run(Thread.java:835)
Information:java: Errors occurred while compiling module 'manifold-sample-rest-api'
Information:javac 12.0.2 was used to compile java sources
Information:10/20/2019 11:20 AM - Build completed with 1 error and 1 warning in 16 s 199 ms
Error:java: Compilation failed: internal java compiler error
Warning:Output path D:\Projects\manifold-sample-rest-api\target\generated-sources\annotations intersects with a source root. Only files that were created by build will be cleaned.

**Comment by rsmckinney** [comment]
@LevT2 Hi.  Looks like you're using a Java 12 JDK.  [The instructions in the README file](https://github.com/manifold-systems/manifold-sample-rest-api) at the root of the project specify a Java 11 JDK.  You can use JDK 12, however you have to change the pom file too, which is also mentioned in the README file. Have a look at the instructions and let me know if you still have questions.  Cheers!

**Comment by LevT2** [comment]
@rsmckinney 
Okay, thank you, you're right, sorry for my novice inattention
