### ISSUE TITLE
Java 8 support

### ISSUE THREAD

**Issue by Lucas-AE** [manifold-systems/manifold-sample-rest-api#4]
I'm trying to implement a client on an java 8 application.  I added the maven-compiler-pluging 
`       <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <compilerArgs>
                        
                        <arg>-Xplugin:Manifold</arg>
                    </compilerArgs>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>systems.manifold</groupId>
                            <artifactId>manifold-graphql</artifactId>
                            <version>${manifold.version}</version>
                        </path>
                        <path>
                            <groupId>systems.manifold</groupId>
                            <artifactId>manifold-exceptions</artifactId>
                            <version>${manifold.version}</version>
                        </path>
                        <path>
                            <groupId>systems.manifold</groupId>
                            <artifactId>manifold-strings</artifactId>
                            <version>${manifold.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>`

it looks like <arg>-Xplugin:Manifold</arg> results in a fatal error. 

Any recommendations on how to resolve?

**Comment by rsmckinney** [comment]
@Lucas-AE  Are you attempting to create a GraphQL client?  There's another example for that: https://github.com/manifold-systems/manifold-sample-graphql-app.  In any case Java 8 does indeed work, if you provide your entire POM file (or your project), I may be able to help.

**Comment by Lucas-AE** [comment]
@rsmckinney Yes i am! I used the example you provided. The example uses java 11 and just changing the version is not working for me. If u could provide the required changes to change the example project from java 11 -> java 8 ?
